name: Auto Assign Pilot Issues

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'pilot')
    steps:
      - name: Assign to Tim
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: jt14den
